---
driver:
  name: ec2
  hostname: bastion.local
driver_config:
  interface: private
  instance_type: t2.medium
  region: us-west-2
  subnet_id: subnet-XXXXXX
  security_group_ids: [ "sg-XXXXXX" ]
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
  tags:
    Environment: dev
    Owner: chef
    Provisioner: test-kitchen
    Service: test-kitchen
    Version: "1.0"
    Zone: private
transport:
  ssh_key: <%= ENV['AWS_SSH_KEY'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.13.37

#verifier:
#  name: inspec
#  sudo: true

platforms:
  - name: centos-7
  - name: rhel-7

suites:
  - name: default
    run_list:
      - recipe[devopsbox::default]
    attributes:
      omnibus_updater:
        version: 12.13.37
