---
driver:
  name: vagrant
  vm_hostname: bastion.local
#driver_config:
#  hostname: bastion.local
#  provider: parallels

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

#verifier:
#  name: inspec
#  sudo: true

platforms:
  - name: ubuntu-16.04
#    driver:
#      box: parallels/ubuntu-16.04
  - name: centos-7.2
#    driver:
#      box: bento/centos-7.2

suites:
  - name: default
    run_list:
      - recipe[devopsbox::default]
    attributes:
      omnibus_updater:
        version: latest
