---
driver:
  name: vagrant
  vm_hostname: devopsbox.local

provisioner:
  name: chef_zero
  require_chef_omnibus: true

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[devopsbox::default]
    attributes:
